apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: default
  labels:
    app: nginx
    service: web
spec:
  containers:
    - image: nginx:1.16
      name: nginx
      imagePullPolicy: Always
